name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: download changes, build and run containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /home/ubuntu/inscriptions/nuxt_inscriptions
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            npm install            
            npm run build            
            pm2 restart NuxtInscriptions
